language: ruby
rvm: 2.1.1
script: 
    - bundle exec jekyll build
    - bundle exec htmlproofer ./_site --only-4xx --url-ignore "/#.*/,/https:\/\/www\.stackoverflow\.com\/.*/"
env:
    global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure