# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: That. Just. Happened.
email: brad.w.turner@gmail.com
description: A product of contemplation
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

source_link: "https://github.com/brandnameboredom/brandnameboredom.github.io"
linkedIn: "https://www.linkedin.com/in/turnerbrad"
stackOverflow: "http://stackoverflow.com/users/70130/brad"
gitHub: "https://github.com/brandnameboredom"
bitBucket: "https://bitbucket.org/brandnameboredom"
gravatar: "https://www.gravatar.com/avatar/cf00ac61fe6597bd1b44fece7b3d9b62"

# Build settings
markdown: kramdown
