version: 1.0.{build}-{branch}

image: Ubuntu

environment:
  matrix:
    - RUBY_VERSION: 32

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build_script:
  - bundle exec jekyll build
