version: 1.0.{build}-{branch}

image: Visual Studio 2022

environment:
  matrix:
    - RUBY_VERSION: 31

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build_script:
  - ruby --version
  - gem --version
  - bundler --version
  - bundle exec jekyll build
